### ISSUE TITLE
Frame does not check if diagnostic file is text

### ISSUE THREAD

**Issue by graysonguarino** [MirServer/ubuntu-frame#107]
```
$ ./frame --diagnostic-path=[an executable]
*Frame will hang for a long time before opening, then becomes unresponsive*
```
If an executable (or any sufficiently large file I imagine) gets passed in to Frame, Frame will freeze as the file is read in and the "text" is rendered. It may be wise to set a size limit to the text file as determining whether a file is an executable or not may be a futile effort.

**Comment by AlanGriffiths** [comment]
Setting a size limit is sensible, but is orthogonal to whether the file is text
