### ISSUE TITLE
question whether support libwebkit2gtk based application

### ISSUE THREAD

**Issue by joyhope** [MirServer/ubuntu-frame#133]
I used  WAYLAND_DISPLAY=wayland-99 macro to control libwebkit2gtk based GUI application, but it does not display in ubuntu-frame.  

ldd for the GUI application showed
`	linux-vdso.so.1 (0x00007ffd3af63000)
	libwebkit2gtk-4.0.so.37 => /lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37 (0x00007fc700c00000)
	libgtk-3.so.0 => /lib/x86_64-linux-gnu/libgtk-3.so.0 (0x00007fc700200000)
	libgdk-3.so.0 => /lib/x86_64-linux-gnu/libgdk-3.so.0 (0x00007fc700af9000)
`
Whether such GUI app is supported by ubuntu frame?

**Comment by Saviq** [comment]
@joyhope try working through this:

https://mir-server.io/docs/packaging-a-gtk3-application-as-an-iot-gui

GTK3 applications do support Wayland, so it should, in theory, work. Not a Frame issue, though, as it's something the application / toolkit must support.

As a backup, you _could_ also package it as an X11 app, but Wayland-native is much preferred:

https://mir-server.io/docs/packaging-an-x11-application-as-an-iot-gui

I'll close this as it's not a Frame problem - please join us for discussion at https://discourse.ubuntu.com/c/mir/15. Thanks!
