### ISSUE TITLE
Disabling cache in wpe-webkit-mir-kiosk

### ISSUE THREAD

**Issue by Eldho1416** [MirServer/ubuntu-frame#136]
I have a angular app running in wpe-webkit-mir-kiosk with the help of Nginx server. 

The UI has Button with call a API GET method to get data, but after i refresh the Angular app the GET method gets called automatically without touching the UI button, what can be the issue?

If it is caching how can i disable caching in wpe-webkit-mir-kiosk

Thanks in advance

**Comment by AlanGriffiths** [comment]
This is a question for the `wpe-webkit-mir-kiosk` maintainer, not an issue with ubuntu-frame

```bash
$ snap info wpe-webkit-mir-kiosk | grep contact
contact:   kontakt@glancr.de
```
