### ISSUE TITLE
Difficult to bootstrap the `display` config option

### ISSUE THREAD

**Issue by Saviq** [MirServer/ubuntu-frame#20]
It's currently difficult to retrieve the defaults for `frame.display`. We point at `/var/snap/ubuntu-frame/current/frame.display`, but that's an internal detail.

It would be good to `snapctl set display …` with the default config, since that what ends up in there anyway?

**Comment by AlanGriffiths** [comment]
Once the display layout is set we don't handle subsequent changes to the physical outputs very well. For now, I'd rather we "opt in" by manually setting a configuration. But I'm very open to ideas for improving this.

**Comment by Saviq** [comment]
Well, since the file is written by ubuntu-frame anyway, it's not really opt-in, is it?

**Comment by AlanGriffiths** [comment]
Well, Mir won't write that file until it runs as a daemon for the first time. As an example, I don't have it on my system.

**Comment by Saviq** [comment]
Sure, but on Ubuntu Core, just installing `ubuntu-frame` makes the current setting the persistent one. But it's still not available through `snap get` until you manually `snap set` it.

**Comment by AlanGriffiths** [comment]
Right, but when do you envisage setting it?

There's file until after Mir has run as a daemon for the first time, so dumping `snapctl set display="$(cat ${display_file})"` in `hooks/configure` would not take effect until a subsequent "configure".

We probably want Mir to do some better change management (e.g. adding any new devices it encounters). And maybe have a "dump out the display config and exit" option too.

**Comment by AlanGriffiths** [comment]
Ah! Yeah, it is a bit weird moving it out of the way only in the configure hook.

You'd be happy if we move the `mv "${display_file}"  "${display_file}.save" || true` incantation from `configure` to `run-frame`? Want to PR that?

**Comment by Saviq** [comment]
But isn't `${display_file}` used when you `snap set ...`, too? That doesn't sound right to move it about?

**Comment by AlanGriffiths** [comment]
Yes, if `$(snapctl get display)` returns something (in `configure`) we write the file.

At present, if `$(snapctl get display)` returns nothing (in `configure`) we move the file out of the way.

Hypothetically, "if `$(snapctl get display)` returns nothing (in `run-frame`) we move the file" would give behaviour you're happy with?
