### ISSUE TITLE
Locks up system if user TTY switches while frame is stopping

### ISSUE THREAD

**Issue by wmww** [MirServer/ubuntu-frame#34]
Reproduce:
- On a classic system, `sudo snap set ubuntu-frame daemon=true`
- TTY switch back to your desktop
- `sudo snap set ubuntu-frame daemon=false`
- Which it's shutting down (it takes a while), switch back to TTY 4
- System is now locked up, can't TTY switch away

**Comment by Saviq** [comment]
This is not Frame-specific, I filed under MirServer/mir#2662.
