### ISSUE TITLE
Missing Fonts in flutter app

### ISSUE THREAD

**Issue by johncharris** [MirServer/ubuntu-frame#42]
I'm cross posting this here since it may be a frame issue. I assume the text rendering is handled by flutter, but they appear correctly when using the gnome compositor.

Environment
Raspberry Pi 4
Ubuntu or Ubuntu Core
Sony elinux embedder

I'm trying to deploy the example application at https://github.com/johncharris/libplctag_dart on Ubuntu Core with Ubuntu-Frame.

I have the snap being built and the app deployed, but there is no text. The titlebar and buttons are empty. I tried adding the google_fonts package and embedding a font but that doesn't work either. The fonts work fine when I run it on a Ubuntu desktop. I'm guessing this means there is a missing dependency, but I have no idea what that might be.

**Comment by AlanGriffiths** [comment]
Hi, neither Ubuntu Core, nor Ubuntu Frame supplies fonts to your application. They need to be supplied by your snap recipe.

As you've not shared that recipe we cannot tell what is wrong with it. Maybe this will help:

https://github.com/MirServer/iot-example-graphical-snap/wiki/Embedding-IOT-GUI-with-Ubuntu-Frame

Flutter is most like the GTK3 example.
