### ISSUE TITLE
Cannot override driver-quirks specified in graphics-core20 provider

### ISSUE THREAD

**Issue by RAOF** [MirServer/ubuntu-frame#9]
The configure hook unconditionally appends the driver-quirks found in `graphics/etc/mir-quirks` to the configuration. Since quirks are additive, there's no way to override the quirks the driver snap specifies.

**Comment by AlanGriffiths** [comment]
I'm not sure of the usecase.

If, as I think is the case you're motivated by, you're working on a driver with a quirks file, then you can unsquashfs the driver snap and use `snap try` the result. That will allow you to modify (or delete) `etc/mir-quirks`.

**Comment by AlanGriffiths** [comment]
In the absence of a good reason to want this, I'm closing the issue
